# Generated by Django 5.2.17 on 2026-09-25 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=10, unique=True, verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('contract_type', models.CharField(choices=[('FIXED', 'Fixed-duration'), ('UNSPECIFIED', 'Unspecified-duration')], default='UNSPECIFIED', max_length=12)),
                ('base_salary', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Base salary (KHR/month)')),
                ('allowance_monthly', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Allowance (KHR/month)')),
                ('dependents', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Dependants (spouse/children)')),
                ('is_resident', models.BooleanField(default=True, verbose_name='Cambodia tax resident')),
                ('nssf_member', models.BooleanField(default=True, verbose_name='NSSF member')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['emp_id'],
            },
        ),
    ]
