# Generated by Django 5.2.17 on 2026-09-25 15:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('advances', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('base', models.DecimalField(decimal_places=0, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('dependents', models.PositiveSmallIntegerField(default=0)),
                ('nssf_member', models.BooleanField(default=True)),
                ('is_resident', models.BooleanField(default=True)),
                ('gross', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nssf_employee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('dependent_allowance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('taxable', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('salary_tax', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('net', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('nssf_employer', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('seniority_accrual', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__emp_id'],
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
